In [1]:
# test
import pandas as pd
file_path = "/root/autodl-tmp/emg2qwerty/logs/conformer_vs_0310/08-58-11/decoding_visualization/test_epoch_200.csv"

data = pd.read_csv(file_path)
pd.set_option('display.max_colwidth', None)
data

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         prediction  \
0  e irowupoglaz oak s rto⏎a oe⏎ etogiors⏎ aaeroet rsaetrrsa  atecaistrt  arsttpraruiest et aser ort⏎s rlasg atugn t s csugaer  aa⌫ ae r ton fattursetatteaaar⏎⌫crrarting ⌫⏎brosig cupvrag sct⌫ r⏎c coura⏎odever⌫c cere⏎aa tiiae⌫cagarsars⌫coacwirf⏎ecraads rrgtaidiatio ecrd⏎rc⌫⌫ s⏎aaesi apeor⏎seatiaa srergrerreserderreased s⏎freysed orsuresola ro⏎prtsycortm,⏎⌫rardee e⌫s⌫eocaois mseo cds i⏎liri edaorr eence ctinties rtaoratweit crsarg ⌫⌫tedctod ,⏎di ceosit ce r⏎asstreaid focsasaktdtradiesai aantees crat⏎edccsi as⏎icae deaaaao⏎t aredd st e sa⏎ccsecs orgut fabegie⌫c rs estato wdoe dee⏎des d⌫rrser⏎artrerei rasrrgdefweectidearot⏎eeesc⌫aeseae aewdas eeeeea⏎ee s ane efr⏎fsalihe ewwh⏎etga⏎lcawi attied fg lgh vetae foed ese f gat the  e⏎aoef r⏎⏎dadr ge⌫⌫femae⏎ ere⏎⏎e ee a⏎ terstiwwir⏎oo⌫alan n odliger aoe⏎gtossit,igaereaareorrere⏎codred⏎ re tar⏎ed ag⏎gi rw ⏎eseokar oeae⌫⌫⏎srrtesgrrrese⌫utoa ⏎aast⌫⌫sr ⌫f soe r⏎kig ⏎eeasldoartara g tg ⏎lfeaaaaee ⏎as

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target  \
0  the quick brown fox jumps over a lazy dog⏎thai adds strategic throw⏎literary mark indivb⌫idual frontpage⏎tiny correctly origin lotus⏎hull titanium bull annex⏎cleaning hdtv properties readers⏎may let;s⌫⌫'s adopt princess⏎chad realistic ultiate f⌫⌫⌫⌫⌫mate d⌫fifth⏎vampire bristol diagnosti =c⌫⌫⌫c journals⏎tile canberra damaged roster⏎percent percentage brilliant nike⏎set u⌫⌫up sheet washer fort⏎pastor douglas modeling chat⏎religions robert sara cotton⏎exposure cherry corners expensive⏎mediterranean tons prod⌫cedure occurred⏎environmental acts affar⌫irs allergy⏎thesarurus ⌫⌫⌫⌫s ⌫⌫⌫⌫urus populations firmware thoughts⏎nails filters routing sunset⏎matthew london italy garbage⏎o⌫contractig po⌫⌫⌫⌫ng posing chile several⏎knights special poverty ogg⌫⌫ffer⏎military bla⌫⌫alance principles dis⌫⌫⌫⌫⌫ distribution⏎disco hours counted lamps⏎penalties adverse does interference⏎livestock suited italia hydraulic⏎surrounding delivered annul⌫ally firer⌫wire⏎maria thinks haen⌫⌫ven later⏎nelson fear steven appears⏎columns closin ⌫g coach keyword⏎emotional monitored architects projector⏎]appointed madness message urge⏎copyright eg=⌫v⌫⌫vent classification everybody⏎boulder o⌫mouse correctk=⌫⌫y⌫ly monitors⏎aware arising shape script⏎designation omaha stored brought⏎torture superintendent realized spoken⏎fired analyzed promote delays⏎doug dimensions poland retro⏎parliamentary court jersey rhythm⏎registar ⌫⌫⌫rar deer effefc⌫⌫ctive equip⌫valent⏎cajm⌫⌫mbodia myself axx⌫is fits⏎delivering extraordinary consequence junction⏎authorities outdoors virtual logic⏎marble lightweight courtesy dvds⏎faring ⌫⌫⌫⌫mig⌫ng migration definition reductions⏎doing filed connector symposium⏎hindu deposit constructed interference⏎transfer outstanding detected asylum⏎orders absent breakfast paris⏎miss mess disturbed focus⏎shanghai life jesse titanium⏎guestbook cruyd⌫⌫de donation conb⌫viction⏎catalog engagement figurte⌫⌫ed pharmacies⏎marie⌫ne guarantees confirm approximate⏎frederick reducing exact cancelled⏎disputes destruction actress adds⏎certificate buii⌫ld mind beneath⏎align balanced expo abortion⏎country rate exotic feat⏎kiss refine disagree normally⏎ch⌫⌫china security syntax cyprus⏎judge printing gabe ⌫⌫⌫ve physical⏎trak⌫ck goto tons mall⏎administration wool express coul'dve⌫⌫⌫⌫d've⏎seas uncertainty anythig⌫ng extensive⏎vault women ha⌫⌫jason cumulative⏎practitioners filters exchanges exception⏎engie⌫neers gerals entering pentium⏎partly coi ⌫n holidays soccer⏎price extension diagnostic harbor⏎promoted harder failure wrong⏎who'll accreditation delaware northeast⏎investments dried immediate kennedy⏎pierce journey mortality subsidary⏎traffic desktops e⌫mm⌫exico residence⏎the qy⌫uick bron⌫wn fox jumps over a al⌫⌫⌫la⌫⌫ lazty⌫⌫y dog⏎most of his work⏎was about number theory⏎and astronomy. those affected⏎have troubnle ⌫⌫⌫⌫le telling the⏎difference between red and⏎green. some players even⏎thought so, and before⏎the final they asked⏎the gypsies to list⏎the curse. the telephone⏎lines went to various⏎locations including radar stations⏎and vaoc lookout posts⏎which reported aircraft locations⏎to the bunker. later,⏎he was forced to⏎disguise his⌫mself as a⏎servant. the reason the⏎male fiddler crab has⏎suchg ⌫⌫ a big claw⏎is to attract ge⌫⌫females.⏎kikyo is the keeper⏎of the jewel and⏎a fair match for⏎inuyasha, he is never⏎able to get the⏎jewel fo⌫rmo⌫⌫om her. superdisk⏎diskettes are etched with⏎a serbo⌫⌫vo pattern at⏎h⌫the factory. the harvesting⏎of biogas is an⏎important role of waste⏎management because methane a⌫us⌫⌫is⏎a greenhouse gas with⏎a greater global warming⏎pro⌫⌫or⌫tential than carbon dioxide.⏎but there is a⏎problem when travellers move⏎across it. using batteries⏎meant tht⌫at the locomotive⏎could not be used⏎on the main railways⏎due to the constant⏎need to charge them.⏎\another idea is that⏎some of the things⏎we use when working⏎out what to do⏎are randon⌫m. a⌫makeuyp⌫⌫p or⏎cose⌫metics ca c=⌫⌫⌫n cover up⏎the parts of the⏎skin with vitiligo. thiws⌫⌫s⏎means that the treaty⏎does ot⌫⌫not protect languages⏎used y⌫by recent immigrants⏎from other countries. one⏎tradition has governed the⏎selection of two most⏎seio⌫⌫nior [ar⌫⌫⌫parts of imf,⌫.⏎frani⌫cis spent some ttime⏎in paris making entirely⏎monochromatic works, but his⏎mature pieces are generally⏎large oil painting ⌫s with⏎splashed or spa⌫lattered areas⏎of bright constrasting co⌫⌫⌫⌫⌫⌫⌫⌫⌫⌫rasting c⌫⌫trasting color.⏎it is made of⏎about half ice and⏎half rock. many wadis⏎have pe⌫ans of alluy⌫vium⏎which rich soil thqt⌫⌫art⌫⌫t⏎are also difficult to⏎cultivate. the two boys⏎were looking for their⏎lost cricket ball which⏎the quick brown fox jumps over a lazy dog

         cer
0  82.018587

In [2]:
print(data['prediction'].str.len())

0    944
Name: prediction, dtype: int64

In [3]:
print(data['target'].str.len())

0    4627
Name: target, dtype: int64

In [5]:
print(data['prediction'])

0    e irowupoglaz oak s rto⏎a oe⏎ etogiors⏎ aaeroet rsaetrrsa  atecaistrt  arsttpraruiest et aser ort⏎s rlasg atugn t s csugaer  aa⌫ ae r ton fattursetatteaaar⏎⌫crrarting ⌫⏎brosig cupvrag sct⌫ r⏎c coura⏎odever⌫c cere⏎aa tiiae⌫cagarsars⌫coacwirf⏎ecraads rrgtaidiatio ecrd⏎rc⌫⌫ s⏎aaesi apeor⏎seatiaa srergrerreserderreased s⏎freysed orsuresola ro⏎prtsycortm,⏎⌫rardee e⌫s⌫eocaois mseo cds i⏎liri edaorr eence ctinties rtaoratweit crsarg ⌫⌫tedctod ,⏎di ceosit ce r⏎asstreaid focsasaktdtradiesai aantees crat⏎edccsi as⏎icae deaaaao⏎t aredd st e sa⏎ccsecs orgut fabegie⌫c rs estato wdoe dee⏎des d⌫rrser⏎artrerei rasrrgdefweectidearot⏎eeesc⌫aeseae aewdas eeeeea⏎ee s ane efr⏎fsalihe ewwh⏎etga⏎lcawi attied fg lgh vetae foed ese f gat the  e⏎aoef r⏎⏎dadr ge⌫⌫femae⏎ ere⏎⏎e ee a⏎ terstiwwir⏎oo⌫alan n odliger aoe⏎gtossit,igaereaareorrere⏎codred⏎ re tar⏎ed ag⏎gi rw ⏎eseokar oeae⌫⌫⏎srrtesgrrrese⌫utoa ⏎aast⌫⌫sr ⌫f soe r⏎kig ⏎eeasldoartara g tg ⏎lfeaaaaee ⏎as
Name: prediction, dtype: object

In [6]:
print(data['target'])

0    the quick brown fox jumps over a lazy dog⏎thai adds strategic throw⏎literary mark indivb⌫idual frontpage⏎tiny correctly origin lotus⏎hull titanium bull annex⏎cleaning hdtv properties readers⏎may let;s⌫⌫'s adopt princess⏎chad realistic ultiate f⌫⌫⌫⌫⌫mate d⌫fifth⏎vampire bristol diagnosti =c⌫⌫⌫c journals⏎tile canberra damaged roster⏎percent percentage brilliant nike⏎set u⌫⌫up sheet washer fort⏎pastor douglas modeling chat⏎religions robert sara cotton⏎exposure cherry corners expensive⏎mediterranean tons prod⌫cedure occurred⏎environmental acts affar⌫irs allergy⏎thesarurus ⌫⌫⌫⌫s ⌫⌫⌫⌫urus populations firmware thoughts⏎nails filters routing sunset⏎matthew london italy garbage⏎o⌫contractig po⌫⌫⌫⌫ng posing chile several⏎knights special poverty ogg⌫⌫ffer⏎military bla⌫⌫alance principles dis⌫⌫⌫⌫⌫ distribution⏎disco hours counted lamps⏎penalties adverse does interference⏎livestock suited italia hydraulic⏎surrounding delivered annul⌫ally firer⌫wire⏎maria thinks haen⌫⌫ven later⏎nelson fear steven appears⏎columns closin ⌫g coach keyword⏎emotional monitored architects projector⏎]appointed madness message urge⏎copyright eg=⌫v⌫⌫vent classification everybody⏎boulder o⌫mouse correctk=⌫⌫y⌫ly monitors⏎aware arising shape script⏎designation omaha stored brought⏎torture superintendent realized spoken⏎fired analyzed promote delays⏎doug dimensions poland retro⏎parliamentary court jersey rhythm⏎registar ⌫⌫⌫rar deer effefc⌫⌫ctive equip⌫valent⏎cajm⌫⌫mbodia myself axx⌫is fits⏎delivering extraordinary consequence junction⏎authorities outdoors virtual logic⏎marble lightweight courtesy dvds⏎faring ⌫⌫⌫⌫mig⌫ng migration definition reductions⏎doing filed connector symposium⏎hindu deposit constructed interference⏎transfer outstanding detected asylum⏎orders absent breakfast paris⏎miss mess disturbed focus⏎shanghai life jesse titanium⏎guestbook cruyd⌫⌫de donation conb⌫viction⏎catalog engagement figurte⌫⌫ed pharmacies⏎marie⌫ne guarantees confirm approximate⏎frederick reducing exact cancelled⏎disputes destruction actress adds⏎certificate buii⌫ld mind beneath⏎align balanced expo abortion⏎country rate exotic feat⏎kiss refine disagree normally⏎ch⌫⌫china security syntax cyprus⏎judge printing gabe ⌫⌫⌫ve physical⏎trak⌫ck goto tons mall⏎administration wool express coul'dve⌫⌫⌫⌫d've⏎seas uncertainty anythig⌫ng extensive⏎vault women ha⌫⌫jason cumulative⏎practitioners filters exchanges exception⏎engie⌫neers gerals entering pentium⏎partly coi ⌫n holidays soccer⏎price extension diagnostic harbor⏎promoted harder failure wrong⏎who'll accreditation delaware northeast⏎investments dried immediate kennedy⏎pierce journey mortality subsidary⏎traffic desktops e⌫mm⌫exico residence⏎the qy⌫uick bron⌫wn fox jumps over a al⌫⌫⌫la⌫⌫ lazty⌫⌫y dog⏎most of his work⏎was about number theory⏎and astronomy. those affected⏎have troubnle ⌫⌫⌫⌫le telling the⏎difference between red and⏎green. some players even⏎thought so, and before⏎the final they asked⏎the gypsies to list⏎the curse. the telephone⏎lines went to various⏎locations including radar stations⏎and vaoc lookout posts⏎which reported aircraft locations⏎to the bunker. later,⏎he was forced to⏎disguise his⌫mself as a⏎servant. the reason the⏎male fiddler crab has⏎suchg ⌫⌫ a big claw⏎is to attract ge⌫⌫females.⏎kikyo is the keeper⏎of the jewel and⏎a fair match for⏎inuyasha, he is never⏎able to get the⏎jewel fo⌫rmo⌫⌫om her. superdisk⏎diskettes are etched with⏎a serbo⌫⌫vo pattern at⏎h⌫the factory. the harvesting⏎of biogas is an⏎important role of waste⏎management because methane a⌫us⌫⌫is⏎a greenhouse gas with⏎a greater global warming⏎pro⌫⌫or⌫tential than carbon dioxide.⏎but there is a⏎problem when travellers move⏎across it. using batteries⏎meant tht⌫at the locomotive⏎could not be used⏎on the main railways⏎due to the constant⏎need to charge them.⏎\another idea is that⏎some of the things⏎we use when working⏎out what to do⏎are randon⌫m. a⌫makeuyp⌫⌫p or⏎cose⌫metics ca c=⌫⌫⌫n cover up⏎the parts of the⏎skin with vitiligo. thiws⌫⌫s⏎means that the treaty⏎does ot⌫⌫not protect languages⏎used y⌫by recent immigrants⏎from other countries. one⏎tradition has governed the⏎selection of two most⏎seio⌫⌫nior [ar⌫⌫⌫parts of imf,⌫.⏎frani⌫cis spent some ttime⏎in paris making entirely⏎monochromatic works, but his⏎mature pieces are generally⏎large oil painting ⌫s with⏎splashed or spa⌫lattered areas⏎of bright constrasting co⌫⌫⌫⌫⌫⌫⌫⌫⌫⌫rasting c⌫⌫trasting color.⏎it is made of⏎about half ice and⏎half rock. many wadis⏎have pe⌫ans of alluy⌫vium⏎which rich soil thqt⌫⌫art⌫⌫t⏎are also difficult to⏎cultivate. the two boys⏎were looking for their⏎lost cricket ball which⏎the quick brown fox jumps over a lazy dog
Name: target, dtype: object

In [ ]:
# validation

In [7]:
import pandas as pd
file_path = "/root/autodl-tmp/emg2qwerty/logs/conformer_vs_0310/08-58-11/decoding_visualization/val_epoch_200.csv"

data = pd.read_csv(file_path)
pd.set_option('display.max_colwidth', None)
data

                   prediction                      target        cer
0                         NaN                         NaN   0.000000
1  the qiick brown fod jumps   the quick brown fox jumps    7.692308
2    ofer a lazy dog⏎spiritua   over a lazy dog⏎spiritual   8.000000
3          l vapoum cootees c         valium committees c  35.000000
4         ontesy⏎atoe jails c       ontest⏎cattle nails c  23.809524

In [10]:
for index, row in data.iterrows():
    print(f"sample {index}: prediction: {row['prediction']}; target: {row['target']}; cer: {row['cer']}")

sample 0: prediction: nan; target: nan; cer: 0.0
sample 1: prediction: the qiick brown fod jumps ; target: the quick brown fox jumps ; cer: 7.6923076923076925
sample 2: prediction: ofer a lazy dog⏎spiritua; target: over a lazy dog⏎spiritual; cer: 8.0
sample 3: prediction: l vapoum cootees c; target:  valium committees c; cer: 35.0
sample 4: prediction: ontesy⏎atoe jails c; target: ontest⏎cattle nails c; cer: 23.809523809523807